server {
    listen 80;
    server_name localhost;

    root /var/www/html/pub;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /static/ {
        location ~ ^/static/version {
            rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
        }

        try_files $uri $uri/ /static.php?resource=$uri&$args;
    }

    location /media/ {
        try_files $uri $uri/ /get.php?$args;
    }

    location ~ ^/(index|get|static|report|404|503)\.php$ {
        try_files $uri =404;

        include fastcgi_params;

        fastcgi_pass php:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_buffer_size 32k;
        fastcgi_buffers 8 32k;
        fastcgi_busy_buffers_size 64k;

        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;
    }

    location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
        expires max;
        access_log off;
        try_files $uri $uri/ /static.php?resource=$uri&$args;
    }

    location ~* /\. {
        deny all;
    }
}